LR_5_Django/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls", namespace='polls')),
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
]

LR_5_Django/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path("", views.IndexView.as_view(), name="index"),
    # ex: /polls/5/
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    # ex: /polls/5/results/
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", views.VoteView.as_view(), name="vote"),
    path("new/", views.PollNewView.as_view(), name="poll_new"),
    # ex: /polls/5/edit/
    path('<int:pk>/edit/', views.PollEditView.as_view(), name='poll_edit'),
    path("login", views.LoginView.as_view(), name="login"),
    path("logout", views.LogoutView.as_view(), name="logout"),
    path("register", views.AccountRegisterView.as_view(), name="register"),
    path("activate/<uidb64>/<token>", views.AccountActivationView.as_view(), name="activate"),
]

LR_5_Django/polls/models.py
from django.db import models
from django.utils import timezone
from django.contrib import admin

import datetime

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published", blank=True, null=True)
    
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    
    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

LR_5_Django/polls/forms.py
from django import forms
from django.utils import timezone
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.contrib.auth.tokens import default_token_generator

from .models import Question, Choice


class QuestionForm(forms.ModelForm):
    choices = forms.CharField(
        label='Question Choices',
        widget=forms.Textarea(attrs={'rows': 7}),
        help_text='Enter the answer options, separating each option with a new line.'
    )

    class Meta:
        model = Question
        fields = ['question_text', 'choices']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance and self.instance.pk:
            choices = '\n'.join(self.instance.choice_set.values_list('choice_text', flat=True))
            self.initial['choices'] = choices

    def clean_choices(self):
        choices = self.cleaned_data.get('choices')
        if choices:
            # Разбить строки по переносу строки и удалить пустые элементы
            choices_list = [choice.strip() for choice in choices.split('\n') if choice.strip()]
            
            # Проверить, чтобы было хотя бы два варианта ответа
            if len(choices_list) < 2:
                raise forms.ValidationError('Enter at least two answer options.')
            
            return choices_list

        return []
    
    def save(self, commit=True):
        question_instance = super().save(commit=False)
        if not question_instance.pub_date:
            question_instance.pub_date = timezone.now()
        question_instance.save()
        
        Choice.objects.filter(question=question_instance).delete()

        choices = self.cleaned_data.get('choices')
        if choices:
            for choice_text in choices:
                Choice.objects.create(question=question_instance, choice_text=choice_text)

        return question_instance


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, request, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.is_active = True
        user.is_superuser = False
        user.is_staff = False
        if commit:
            user.save()
            # self.send_verification_email(user, request)
        return user
    
    # def send_verification_email(self, user, request):
    #     current_site = get_current_site(request)
    #     mail_subject = 'Activate your account'
    #     message = render_to_string(
    #         'polls/verification_email.html',
    #         {
    #             'user': user,
    #             'domain': current_site.domain,
    #             'uid': urlsafe_base64_encode(force_bytes(user.pk)),
    #             'token': default_token_generator.make_token(user),
    #         }
    #     )
    #     email = EmailMessage(mail_subject, message, to=[user.email])
    #     email.content_subtype = "html"
    #     email.send()

LR_5_Django/polls/views.py
import random
import logging

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import View, generic
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.views import redirect_to_login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from django.http import HttpResponse
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_decode
from django.utils.encoding import force_str
from django.contrib.auth.models import User

from .forms import NewUserForm

from .models import Choice, Question
from .forms import QuestionForm


SLOGANS = [
    "Polls or Trolls: Without your choice, beware the gremlins' voice!",
    "Polls or Spooks: Don't let phantoms choose your folks!",
    "Polls or Ghouls: Vote or let the underworld fool!",
    "Polls or Wraiths: Make a choice or invite spectral straits!",
    "Polls or Shadows: Without your say, darkness grows!",
    "Polls or Beasts: Choose wisely, or unleash monstrous feasts!",
    "Polls or Nightmares: Cast your vote, or fall into horror's lairs!",
    "Polls or Ghosts: Decide or invite the haunted costs!",
    "Polls or Fiends: Without your voice, chaos reigns!",
    "Polls or Vampires: Your choice could calm the nocturnal pyres!",
    "Polls or Goblins: Without a vote, mischief unfolds in!",
    "Polls or Crows: Cast your choice or let dark omens rise!",
    "Polls or Skeletons: A vote unsaid releases bone-ridden threats!",
    "Polls or Serpents: Fail to choose, and risk subterranean events!",
    "Polls or Abyss: A silent electorate summons the darkness!"
]


class PollsBaseView(View):
    slogans = SLOGANS

    def get_slogan(self):
        return random.choice(self.slogans)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['slogan'] = self.get_slogan()
        return context


class IndexView(PollsBaseView, generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[
            :5
        ]


class DetailView(PollsBaseView, generic.DetailView):
    model = Question
    template_name = "polls/detail.html"
    
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(PollsBaseView, generic.DetailView):
    model = Question
    template_name = "polls/results.html"


class VoteView(PollsBaseView, View):
    def post(self, request, question_id):
        question = get_object_or_404(Question, pk=question_id)
        try:
            selected_choice = question.choice_set.get(pk=request.POST["choice"])
        except (KeyError, Choice.DoesNotExist):
            # Redisplay the question voting form.
            return render(
                request,
                "polls/detail.html",
                {
                    "slogan": self.get_slogan(),
                    "question": question,
                    "error_message": "You didn't select a choice.",
                },
            )
        else:
            selected_choice.votes += 1
            selected_choice.save()
            # Always return an HttpResponseRedirect after successfully dealing
            # with POST data. This prevents data from being posted twice if a
            # user hits the Back button.
            return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))


class UserIsStaffMixin(UserPassesTestMixin):
    login_url = "polls:login"
    redirect_field_name = "next"
    raise_exception = False

    def test_func(self):
        return self.request.user.is_staff

    def handle_no_permission(self):
        if self.raise_exception:
            raise PermissionDenied(self.get_permission_denied_message())
        # next_url = self.request.path
        # return redirect(self.login_url, f"{self.redirect_field_name}={next_url}")
        return redirect_to_login(self.request.get_full_path(), self.login_url, self.redirect_field_name)
        # return redirect('{}?{}={}'.format(reverse(self.login_url), self.redirect_field_name, next_url))


class PollNewView(PollsBaseView, UserIsStaffMixin, LoginRequiredMixin, View):
    
    def get(self, request):
        form = QuestionForm()
        return render(
            request,
            'polls/poll_new_edit.html',
            {
                'form': form,
                "slogan": self.get_slogan(),
            }
        )

    def post(self, request):
        form = QuestionForm(request.POST)
        if form.is_valid():
            poll = form.save(commit=False)
            poll.save()
            return redirect('polls:detail', pk=poll.pk)
        return render(
            request,
            'polls/poll_new_edit.html',
            {
                'form': form,
                "slogan": self.get_slogan(),
            }
        )

class PollEditView(PollsBaseView, UserIsStaffMixin, LoginRequiredMixin, View):
    
    def get(self, request, pk):
        poll = get_object_or_404(Question, pk=pk)
        form = QuestionForm(instance=poll)
        return render(
            request, 'polls/poll_new_edit.html', {
                "slogan": self.get_slogan(),
                'form': form
            }
        )

    def post(self, request, pk):
        poll = get_object_or_404(Question, pk=pk)
        form = QuestionForm(request.POST, instance=poll)
        if form.is_valid():
            poll = form.save(commit=False)
            poll.pub_date = timezone.now()
            poll.save()
            return redirect('polls:detail', pk=poll.pk)
        return render(
            request, 'polls/poll_new_edit.html', {
                "slogan": self.get_slogan(),
                'form': form
            }
        )


class LoginView(PollsBaseView, View):
    logger = logging.getLogger(__name__)
    
    def get(self, request):
        form = AuthenticationForm()
        return render(request=request, template_name="polls/login.html", context={"login_form": form})

    def post(self, request):
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                next_url = self.request.GET.get('next')
                if next_url:
                    return redirect(next_url)
                else:
                    return redirect('polls:index')
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
        
        slogan = self.get_slogan()
        # logger.warning(f"Slogan {slogan}.")
        return render(
            request=request,
            template_name="polls/login.html",
            context={
                "slogan": slogan,
                "login_form": form
            }
        )


class LogoutView(View):
    def get(self, request):
        logout(request)
        messages.info(request, "You have successfully logged out.")
        return redirect("polls:index")


class AccountRegisterView(View):
    form_class = NewUserForm
    template_name = "polls/register.html"

    def get(self, request):
        form = self.form_class()
        return render(request=request, template_name=self.template_name, context={"register_form": form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(request)
            messages.success(request, f"Registration successful.")
            return redirect("polls:index")

        messages.error(request, "Unsuccessful registration. Invalid information.")
        return render(request=request, template_name=self.template_name, context={"register_form": form})


class AccountActivationView(View):
    def get(self, request, uidb64, token):
        # messages.error(request, f"uidb64 = {uidb64}, token = {token}")
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            # messages.error(request, f"uid = {uid}")
            user = User.objects.get(pk=uid)
            # messages.error(request, f"user = {user}")
        except:
            user = None
        
        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            return render(request, 'polls/account_activation_success.html')
        else:
            return render(request, 'polls/account_activation_failure.html')


# def login_request(request):
# 	if request.method == "POST":
# 		form = AuthenticationForm(request, data=request.POST)
# 		if form.is_valid():
# 			username = form.cleaned_data.get('username')
# 			password = form.cleaned_data.get('password')
# 			user = authenticate(username=username, password=password)
# 			if user is not None:
# 				login(request, user)
# 				messages.info(request, f"You are now logged in as {username}.")
# 				return redirect("polls:index")
# 			else:
# 				messages.error(request,"Invalid username or password.")
# 		else:

LR_5_Django/polls/templates/polls/account_activation_failure.html
{% extends "polls/base.html" %}

{% block content %}      

    <h1>Account Activation Failed</h1>
    <p>We were unable to activate your account. The activation link is invalid or has expired.</p>
    <p>Please <a href="{% url 'polls:register' %}">register</a> again or contact support if you need assistance.</p>

{% endblock %}

LR_5_Django/polls/templates/polls/account_activation_success.html
{% extends "polls/base.html" %}

{% block content %}      

    <h1>Account Activation Successful</h1>
    <p>Congratulations! Your account has been successfully activated.</p>
    <p>You may now <a href="{% url 'polls:login' %}">login</a> to start using your account. Enjoy!</p>

{% endblock %}

LR_5_Django/polls/templates/polls/base.html
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Polls from the Crypt</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    </head>
    <body>
        <div class="page-header">
            {% if user.is_authenticated %}
                {% if user.is_staff %}
                    <a href="{% url 'polls:poll_new' %}" class="top-menu">
                        <span style="color: white">
                            <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                            </svg>
                        </span>
                    </a>
                {% endif %}
                <a href="{% url 'polls:logout' %}" class="top-menu">
                    <span style="color: white">
                        <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-box-arrow-left" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0v2z"/>
                            <path fill-rule="evenodd" d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z"/>
                        </svg>
                    </span>
                </a>
                <a href="#" class="top-menu-welcome">
                    <span style="color: white">Welcome, {{user.username}}</span>
                </a>
            {% else %}
                <div style="vertical-align: middle">
                    <a href="{% url 'polls:register' %}" class="top-menu">
                        <span style="color: white">
                            <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-box-arrow-in-up" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M3.5 10a.5.5 0 0 1-.5-.5v-8a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 0 0 1h2A1.5 1.5 0 0 0 14 9.5v-8A1.5 1.5 0 0 0 12.5 0h-9A1.5 1.5 0 0 0 2 1.5v8A1.5 1.5 0 0 0 3.5 11h2a.5.5 0 0 0 0-1h-2z"/>
                                <path fill-rule="evenodd" d="M7.646 4.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 5.707V14.5a.5.5 0 0 1-1 0V5.707L5.354 7.854a.5.5 0 1 1-.708-.708l3-3z"/>
                            </svg>
                        </span>
                    </a>
                    <a href="{% url 'polls:login' %}" class="top-menu">
                        <span style="color: white">
                            <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-box-arrow-in-right" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0v-2z"/>
                                <path fill-rule="evenodd" d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
                            </svg>
                        </span>
                    </a>
                </div>
            {% endif %}
            <h1><a href="/polls">Polls from the Crypt</a></h1>
            <h4><a href="/polls">{{ slogan }}</a></h4>
        </div>

        <!-- Messages -->
        <div class="container">
            {% if messages %}
                <div class="alert alert-info alert-dismissible fade show" role="alert">
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}
        </div>

        <div class="content container mt-4, alpha60">
            <div class="row">
                <div class="col-md-8">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </body>
</html>

LR_5_Django/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset class="alpha60">
            <legend>
                <h1>{{ question.question_text }}</h1>
                {% if question.pub_date %}
                    <div class="date">
                        {{ question.pub_date }}
                    </div>
                {% endif %}
                {% if user.is_staff %}
                    <a class="btn btn-default" href="{% url 'polls:poll_edit' pk=question.pk %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                            <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                        </svg>
                    </a>
                {% endif %}
            </legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" class="btn btn-dark" value="Vote">
    </form>
{% endblock %}

LR_5_Django/polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content %}
    {% if latest_question_list %}
        {% for question in latest_question_list %}
            <div class="poll">
                <h4><a href="{% url 'polls:detail' pk=question.pk %}">{{ question.question_text|linebreaksbr }}</a></h4>
                <div class="date">
                    <p>Date: '{{ question.pub_date }}'</p>
                </div>
                <hr>
            </div>
        {% endfor %}
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock %}

LR_5_Django/polls/templates/polls/login.html
{% extends "polls/base.html" %}

{% block content %}      

    {% load crispy_forms_tags %}

    <!--Login-->
    <div class="py-5">
        <h1>Login</h1> {{slogan}}
        <form method="POST">
            {% csrf_token %}
            {{ login_form|crispy }}
            <button class="btn btn-primary" type="submit">Login</button>
        </form>
        <p class="text-center">Don't have an account? <a href="{% url 'polls:register' %}">Create an account</a>.</p>
    </div>

{% endblock %}

LR_5_Django/polls/templates/polls/poll_new_edit.html
{% extends 'polls/base.html' %}

{% block content %}

    {% load crispy_forms_tags %}

    <h1>Poll</h1>
    <form method="POST" class="poll-form">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="save btn btn-info">Save</button>
    </form>
{% endblock %}

LR_5_Django/polls/templates/polls/register.html
{% extends "polls/base.html" %}

{% block content %} 

    {% load crispy_forms_tags %}         

    <div class="py-5">
        <h1>Register</h1>
        <form method="POST">
            {% csrf_token %}
            {{ register_form|crispy }}                    
            <button class="btn btn-primary" type="submit">Register</button>
        </form>
        <p class="text-center">If you already have an account, <a href="{% url 'polls:login' %}">login</a> instead.</p>
    </div>

{% endblock %}

LR_5_Django/polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block content %}
    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}